version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/circleci-python
    environment:
      BASH_ENV: ~/.bashrc
    docker:
      - image: circleci/python:3.7.3
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout # check out source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      - run: sudo apt install -y nodejs
      - run: mkdir ~/.npm-global && npm config set prefix '~/.npm-global'
      - run: export PATH=~/.npm-global/bin:$PATH && echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
      - run: npm install svgexport -g
      - restore_cache:
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          command: |

            echo "$PATH"
            pipenv run pytest